[package]
name = "madaboost"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
rayon           = { workspace = true }
miniboosts_core = { path = "../../miniboosts-core" }
hypotheses      = { path = "../../hypotheses" }


[dev-dependencies]
decision_tree   = { path = "../../weak-learners/decision-tree" }
