[package]
name = "logging"
version = "0.1.0"
edition = "2024"

[dependencies]
rand            = { version = "0.8.5" }
rayon           = { version = "1.10.0" }
colored         = { version = "2.1.0" }
miniboosts_core = { path = "../miniboosts-core" }
optimization    = { path = "../optimization" }

