[package]
name = "mlpboost"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
miniboosts_core      = { path = "../../miniboosts-core" }
hypotheses           = { path = "../../hypotheses" }
optimization         = { path = "../../optimization" }
corrective_erlpboost = { path = "../corrective-erlpboost" }


[dev-dependencies]
decision_tree        = { path = "../../weak-learners/decision-tree" }
