[package]
name = "totalboost"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
miniboosts_core = { path = "../../miniboosts-core" }
hypotheses      = { path = "../../hypotheses" }
softboost       = { path = "../softboost" }


[dev-dependencies]
decision_tree   = { path = "../../weak-learners/decision-tree" }
