[package]
name = "hypotheses"
version = "0.1.0"
edition = "2024"

[dependencies]
serde           = { version = "1.0.206", features = ["rc", "derive"] }
fixedbitset     = { version = "0.5.7" }
miniboosts_core = { path = "../miniboosts-core" }

